### ISSUE TITLE
support Twine `if` syntax

### ISSUE THREAD

**Issue by lordmortis** [StirfireStudios/Jacquard-YarnParser#10]
@distantcam can we support twine's `if` syntax?
so that's `<< if $something and if $something else >>` 

I'm happy for ifs to just be dropped from expressions - that seems the cleanest way to do it
(which means `<< set $var to if 1+1 >>` would work)

**Comment by distantcam** [comment]
@lordmortis I'm not sure what you mean here. The antlr already supports this syntax. I don't understand what's broken.

**Comment by lordmortis** [comment]
This was causing issues and will not be implemented
